# Generated by Django 3.1.3 on 2021-10-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosxxi',
            name='img_producto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='ingredientesxxi',
            name='ingrediente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredientesxxi',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
