# Generated by Django 3.1.3 on 2021-10-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211025_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopagoxxi',
            name='tipo_pago',
            field=models.CharField(max_length=50),
        ),
    ]
