# Generated by Django 3.1.3 on 2021-10-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211026_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosxxi',
            name='tipo_producto_xxi_id_tipo_producto',
        ),
        migrations.AddField(
            model_name='productosxxi',
            name='tipo_pago',
            field=models.IntegerField(null=True),
        ),
    ]
