# Generated by Django 3.1.3 on 2021-10-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211026_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaxxi',
            name='tipo_pago',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
