# Generated by Django 3.1.3 on 2021-10-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_facturasxxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaxxi',
            name='media',
            field=models.FileField(null=True, upload_to='facturas'),
        ),
    ]
