# Generated by Django 3.1.3 on 2021-10-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211028_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientesxxi',
            name='issue_quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredientesxxi',
            name='receive_quantity',
            field=models.IntegerField(default='0'),
        ),
    ]
