# Generated by Django 3.1.3 on 2021-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211029_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedoresXxi2',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
