# Generated by Django 3.1.3 on 2021-11-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_proveedoresxxi2'),
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIOS_DESKTOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('NOMBRE', models.CharField(max_length=80)),
                ('TIPO_USUARIO', models.CharField(max_length=50)),
            ],
        ),
    ]
