# Generated by Django 3.1.3 on 2021-11-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_usuarios_desktop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedoresxxi2',
            name='correo',
            field=models.CharField(max_length=50),
        ),
    ]
