# Generated by Django 3.1.3 on 2021-11-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211104_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestXxi',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.BigIntegerField()),
                ('img_producto', models.ImageField(null=True, upload_to='productos')),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
