# Generated by Django 3.1.3 on 2021-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_testxxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaxxi',
            name='media',
            field=models.FileField(null=True, upload_to='facturas'),
        ),
    ]
