# Generated by Django 3.1.3 on 2021-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20211113_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=800)),
                ('acumulado', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.BigIntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
