# Generated by Django 3.1.3 on 2021-11-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_ordenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordenes',
        ),
    ]
