# Generated by Django 3.1.3 on 2021-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_ordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientesxxi',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
