# Generated by Django 3.1.3 on 2021-11-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_ingredientesxxi_export_to_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='acumulado',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='detalle',
        ),
        migrations.CreateModel(
            name='detalle_ordenes',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=800)),
                ('acumulado', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ordenes')),
            ],
        ),
    ]
