# Generated by Django 3.1.3 on 2021-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20211123_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='testig_detalle',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=800)),
                ('acumulado', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
