# Generated by Django 3.1.3 on 2021-11-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_testig_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_ordenes',
            old_name='id_orden',
            new_name='id_ordenn',
        ),
    ]
