# Generated by Django 3.1.3 on 2021-11-24 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20211123_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_ordenes',
            name='datefield',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenes',
            name='datefield',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
