# Generated by Django 3.1.3 on 2021-11-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20211124_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_ordenes',
            name='id_ordenn',
        ),
    ]
