# Generated by Django 3.1.3 on 2021-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_detalle_ordenes_id_ordenn'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_ordenes',
            name='id_orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
