# Generated by Django 3.1.3 on 2021-11-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_detalle_ordenes_id_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_ordenes',
            name='id_orden',
        ),
    ]
