# Generated by Django 3.1.3 on 2021-11-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_detalle_ordenes_id_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_ordenes',
            name='id_orde',
            field=models.IntegerField(default=1),
        ),
    ]
