# Generated by Django 3.1.3 on 2021-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_detalle_ordenes_id_orde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_ordenes',
            name='id_orde',
            field=models.IntegerField(default=''),
        ),
    ]
