# Generated by Django 3.1.3 on 2021-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20211124_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_ordenes',
            name='nombre_pedido',
            field=models.CharField(default='(null)', max_length=80),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='nombre_pedido',
            field=models.CharField(default='(null)', max_length=80),
        ),
    ]
