# Generated by Django 3.1.3 on 2021-11-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211125_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_ordenes',
            name='id_orde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_orde', to='main.ordenes'),
        ),
    ]
