# Generated by Django 3.1.3 on 2021-11-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20211126_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('rut', models.IntegerField()),
                ('numero_cuenta', models.IntegerField()),
                ('tipo_cuenta', models.CharField(max_length=50)),
            ],
        ),
    ]
