# Generated by Django 3.1.3 on 2021-12-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_grafic'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
