# Generated by Django 3.1.3 on 2021-12-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_proveedores_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
