# Generated by Django 3.1.3 on 2021-12-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_ordenes_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='date',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
