# Generated by Django 3.1.3 on 2021-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_ordenes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaxxi',
            name='fecha_fact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
