# Generated by Django 3.1.3 on 2021-12-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_facturaxxi_fecha_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosxxi',
            name='reseta',
            field=models.CharField(default=None, max_length=800),
            preserve_default=False,
        ),
    ]
